# This is the schema that will be passed to the LLM for Cypher generation

GRAPH_SCHEMA = """
Nodes:
  - DataProduct(id, name, type, source, description, short_description, destination, domain, subdomain, environment, schedule)
  - Tag(name)
  - BusinessTerm(name)
  - Glossary(name)
  - KnownIssue(name)
  - Documentation(name)
  - FAQ(name)
  - Query(name)
  - Table(name)
  - PIIField(name)
  - Owner(<attributes>)
  - Manager(<attributes>)
  - Metrics(<attributes>)
  - DataQuality(<attributes>)
  - Classification(<attributes>)
  - UsageStats(<attributes>)
  - Team(<attributes>)
  - AccessControl(<attributes>)
  - Database(<attributes>)
  - Schema(<attributes>)
  - Steward(<attributes>)
  - Consumer(<attributes>)
  - Policy(<attributes>)
  - Pipeline(name, <other attributes>)
  - Job(<attributes>)
  - FieldLineage(<attributes>)
  - ChangeLog(timestamp, field, old_value, new_value)

Relationships:
  - (DataProduct)-[:HAS_TAG]->(Tag)
  - (DataProduct)-[:HAS_TERM]->(BusinessTerm)
  - (DataProduct)-[:GLOSSARY_LINK]->(Glossary)
  - (DataProduct)-[:HAS_ISSUE]->(KnownIssue)
  - (DataProduct)-[:HAS_DOC]->(Documentation)
  - (DataProduct)-[:HAS_FAQ]->(FAQ)
  - (DataProduct)-[:HAS_QUERY]->(Query)
  - (DataProduct)-[:USES_TABLE]->(Table)
  - (DataProduct)-[:HAS_PII]->(PIIField)
  - (DataProduct)-[:OWNED_BY]->(Owner)
  - (DataProduct)-[:MANAGED_BY]->(Manager)
  - (DataProduct)-[:HAS_METRIC]->(Metrics)
  - (DataProduct)-[:HAS_QUALITY]->(DataQuality)
  - (DataProduct)-[:CLASSIFIED_AS]->(Classification)
  - (DataProduct)-[:HAS_USAGE]->(UsageStats)
  - (DataProduct)-[:PART_OF_TEAM]->(Team)
  - (DataProduct)-[:HAS_ACCESS_CTRL]->(AccessControl)
  - (DataProduct)-[:STORED_IN]->(Database)
  - (DataProduct)-[:HAS_SCHEMA]->(Schema)
  - (DataProduct)-[:STEWARDED_BY]->(Steward)
  - (DataProduct)-[:CONSUMED_BY]->(Consumer)
  - (DataProduct)-[:HAS_POLICY]->(Policy)
  - (DataProduct)-[:HAS_PIPELINE]->(Pipeline)
  - (DataProduct)-[:HAS_JOB]->(Job)
  - (DataProduct)-[:HAS_FIELD_LINEAGE]->(FieldLineage)
  - (DataProduct)-[:FEEDS_INTO]->(DataProduct)
  - (Pipeline)-[:TRIGGERS]->(Pipeline)
  - (Pipeline)-[:PRODUCES]->(DataProduct)
  - (DataProduct)-[:HAS_CHANGE_LOG]->(ChangeLog)
"""