updatable_fields:
  - name
  - type
  - description
  - short_description
  - destination
  - tables
  - pipelines
  - owner
  - manager
  - domain
  - subdomain
  - metrics
  - data_quality
  - data_classification
  - tags
  - business_terms
  - glossary_links
  - schema
  - usage_stats
  - known_issues
  - stewards
  - consumers
  - team
  - policies
  - access_controls
  - pii_fields
  - database
  - environment
  - jobs
  - schedule
  - documentation_links
  - faqs
  - sample_queries
  - upstream_sources
  - downstream_targets
  - field_lineage